apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-pwf-vault/items/aiven-kafka"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: viken-no-fint-flyt-history-service
spec:
  itemPath: "vaults/aks-pwf-vault/items/flyt-demo-fint-flyt-history-service"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-history-service
  name: fint-flyt-history-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-history-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-history-service
  name: fint-flyt-history-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-history-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-history-service
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-history-service:dummy
          name: fint-flyt-history-service
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
            - secretRef:
                name: flyt-demo-fint-flyt-history-service
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M' }
            - { name: fint.org-id, value: 'pwf.no' }
            - { name: spring.datasource.hikari.schema, value: 'pwf_no' }