fint:
  application-id: fint-flyt-history-service
server:
  max-http-header-size: 40KB
spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - flyt-resource-server
      - flyt-postgres