fint:
  kafka:
    topic:
      org-id: fintlabs.no
      domain-context: flyt
    application-id: fint-skjema-case-history-service
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-skjema-case-history-service
  datasource:
    url: jdbc:postgresql://localhost:5434/fint-skjema-case-history-service-postgres
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
server:
  port: 8084
generateTestData: false
